colorscheme dedelala

set global ui_options ncurses_enable_mouse=false ncurses_assistant=cat ncurses_set_title=false

set global indentwidth 8
set global tabstop 8
set global aligntab false
set global scrolloff 4,4

hook global WinCreate .* %{
    addhl window/ show-matching
    addhl window/ number-lines -relative -hlcursor -separator "  "
    addhl window/ column 81 white,rgb:2d0040
    addhl window/ dynregex \h+$ 0:black,rgb:545453
    addhl window/ dynregex ^\t* 0:black,rgb:2d0040
    addhl window/ dynregex ^\ * 0:black,rgb:000f40
    addhl window/ dynregex \ +\t+\ * 0:black,rgb:d22323
    addhl window/ dynregex \t+\ +\t* 0:black,rgb:d22323
    map window user -docstring "<--" , :buffer-previous<ret>
    map window user -docstring "-->" . :buffer-next<ret>
    map window user -docstring "blame" b :git\ blame<ret>
    map window user -docstring "hide blame" n :git\ hide-blame<ret>
    map window user -docstring "diff" d :git\ diff<ret>
    map window user -docstring "comment" c :comment-line<ret>
    map window user -docstring "lint" l :lint<ret>:buffer\ *lint-output*<ret>
    map window user -docstring "make" m :make<ret>:buffer\ *make*<ret>
    map window user -docstring "split" <space> :split<ret>
    map window user -docstring "shell" <tab> :shell<ret>
    map window user -docstring "next conflict" x /^<lt>{7}<ret>?^<gt>{7}<ret>Gl
    map window user -docstring "resolve keep a" <lt> s^<lt>{7}<ret>Xd/^={7}<ret>?^<gt>{7}<ret>Xd
    map window user -docstring "resolve keep b" <gt> s^<lt>{7}<ret>?^={7}<ret>Xd/^<gt>{7}<ret>Xd
}

define-command shell %{ nop %sh{
    cd "$(dirname "$kak_buffile")"
    st &
}}

define-command split %{ evaluate-commands %sh{
    if [ $kak_client = client0 ]; then
        echo rename-client adelaide
        echo new rename-client brunhilde
        exit
    fi

    for c in brunhilde cassandra desdemona esperanza friedegarde; do
        case $kak_client_list in
        *"$c"*) ;;
        *)
            echo new rename-client $c
            exit
            ;;
        esac
    done

    echo echo you have enough
}}

hook global KakBegin .* %sh{
    echo rename-session \"$(basename "$PWD")\"
}

hook global BufWritePost .* git\ show-diff

eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=go %{
    lsp-enable-window
    map global normal . :enter-user-mode\ lsp<ret>
    set window makecmd 'go build'
    set window disabled_hooks .*-indent
    hook buffer BufWritePre .* %{
        lsp-formatting-sync
    }
}

hook global WinSetOption filetype=sh %{
    set window lintcmd 'shellcheck -fgcc -Cnever'
    lint-enable
    hook buffer BufWritePost .* lint
}

hook global WinSetOption filetype=yaml %{
    set window indentwidth 2
    set window tabstop 2
    set window lintcmd 'yamllint -d ~/.yamllint.yml -f parsable "$kak_buffile"'
    lint-enable
    hook buffer BufWritePost .* lint
}

hook global WinSetOption filetype=html %{
    set window indentwidth 4
    set window tabstop 4
}
