#!/bin/bash

hc() {
    herbstclient "$@"
}

# keybindings
Mod=Mod4

hc keybind XF86AudioMute spawn amixer -D "hw:1" sset Master playback toggle-mute
hc keybind XF86AudioRaiseVolume spawn amixer -D "hw:1" sset Master playback 3dB+
hc keybind XF86AudioLowerVolume spawn amixer -D "hw:1" sset Master playback 3dB-

hc keybind $Mod-v and , \
        use mixer , \
        compare tags.by-name.mixer.client_count lt 1 , \
        spawn st alsamixer -D "hw:1"

hc keybind $Mod-r use rack
