#!/bin/bash

hc() {
    herbstclient "$@"
}

# hc and , compare tags.by-name.fox.client_count = 0 \
#        , use fox , spawn env MOZ_USE_XINPUT2=1 apulse firefox

hc and , compare tags.by-name.fox.client_count = 0 \
       , use fox , spawn google-chrome-stable

