#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#2d0040'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close_and_remove

# basic movement
# focusing clients
hc keybind $Mod-a     focus left
hc keybind $Mod-s     focus down
hc keybind $Mod-w     focus up
hc keybind $Mod-d     focus right

# moving clients
hc keybind $Mod-Shift-a     shift left
hc keybind $Mod-Shift-s     shift down
hc keybind $Mod-Shift-w     shift up
hc keybind $Mod-Shift-d     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

hc keybind $Mod-e       chain , split bottom 0.5 , focus down , spawn ${TERMINAL:-st}
hc keybind $Mod-Shift-e chain , split right 0.5 , focus right , spawn ${TERMINAL:-st}

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-a       resize left +$resizestep
hc keybind $Mod-Control-s       resize down +$resizestep
hc keybind $Mod-Control-w       resize up +$resizestep
hc keybind $Mod-Control-d       resize right +$resizestep

# tags
# tag_names=( {1..9} )
# tag_keys=( {1..9} 0 )

# hc rename default "${tag_names[0]}" || true
# for i in ${!tag_names[@]} ; do
#     hc add "${tag_names[$i]}"
#     key="${tag_keys[$i]}"
#     if ! [ -z "$key" ] ; then
#         hc keybind "$Mod-$key" use_index "$i"
#         hc keybind "$Mod-Shift-$key" move_index "$i"
#     fi
# done

hc rename default cube
hc keybind $Mod-1 and , use cube \
        , compare tags.focus.client_count = 0 , spawn st
hc keybind $Mod-2 and , add hammer , use hammer \
        , compare tags.focus.client_count = 0 , spawn st
hc keybind $Mod-3 and , add shield , use shield \
        , compare tags.focus.client_count = 0 , spawn st
hc keybind $Mod-f and , add fox , use fox \
        , compare tags.focus.client_count = 0 \
        , spawn env MOZ_USE_XINPUT2=1 apulse firefox

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-space floating toggle
hc keybind $Mod-Return fullscreen toggle
hc keybind $Mod-p pseudotile toggle

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_width 4
hc set frame_border_active_color '#ffafc7'
hc set frame_border_normal_color '#74d7ec'
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 16

hc attr theme.active.color '#ffafc7'
hc attr theme.normal.color '#74d7ec'
hc attr theme.urgent.color '#ee925d'
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 0
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#ffafc7'
hc attr theme.active.outer_color '#ffafc7'
hc attr theme.normal.inner_color '#74d7ec'
hc attr theme.normal.outer_color '#74d7ec'
hc attr theme.background_color '#2d0040'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0


# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class~'Firefox' tag=fox
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

hc and , compare tags.by-name.cube.client_count = 0 , use cube , spawn st
