#!/usr/bin/env bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#2d0040'

hc detect_monitors
read -r _ _ w h <<< "$(hc monitor_rect)"
fill="${w}x${h}"
left="$((w/2))x${h}"
right="$((w/2))x${h}+$((w/2))"

hc set default_frame_layout 2

hc add kitty
hc merge_tag default kitty
hc add fox

hc set_monitors "$fill" "$fill"
hc rename_monitor 0 main
hc rename_monitor 1 alt


# keybindings
hc keyunbind --all
Mod=Mod4

hc keybind $Mod-Shift-q    quit
hc keybind $Mod-Shift-r    reload
hc keybind $Mod-Shift-c    close_and_remove
hc keybind $Mod-Shift-x    remove
hc keybind $Mod-x          split explode
hc keybind $Mod-space      floating toggle
hc keybind $Mod-Return     fullscreen toggle
hc keybind $Mod-p          pseudotile toggle
hc keybind $Mod-z          cycle
hc keybind $Mod-i          jumpto urgent
hc keybind $Mod-Control-f  set_monitors "$fill" "$fill"

hc keybind $Mod-Tab and \
        , raise_monitor main , focus_monitor main \
        , use kitty , compare tags.focus.client_count = 0 , spawn kitty

hc keybind $Mod-f and \
        , raise_monitor alt , focus_monitor alt \
        , use fox , compare tags.focus.client_count = 0 \
        , spawn env MOZ_USE_XINPUT2=1 apulse firefox

hc keybind $Mod-Shift-f and \
        , set_monitors "$left" "$right" \
        , raise_monitor alt , focus_monitor alt \
        , use fox , compare tags.focus.client_count = 0 \
        , spawn env MOZ_USE_XINPUT2=1 apulse firefox


# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_width 4
hc set frame_border_active_color '#ffafc7'
hc set frame_border_normal_color '#74d7ec'
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 16

hc attr theme.active.color '#ffafc7'
hc attr theme.normal.color '#74d7ec'
hc attr theme.urgent.color '#ee925d'
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 0
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#ffafc7'
hc attr theme.active.outer_color '#ffafc7'
hc attr theme.normal.inner_color '#74d7ec'
hc attr theme.normal.outer_color '#74d7ec'
hc attr theme.background_color '#2d0040'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0


# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class~'Firefox' tag=fox
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

hc set tree_style '╾│ ├└╼─┐'


# unlock, just to be sure
hc unlock

hc pad main 50
hc pad alt 50
hermes -l -s '  ' -p bar bar | lemonbar \
        -B '#00000000' \
        -f "Go Regular:size=12" \
        -f "Font Awesome 5 Free:style=Regular:size=16" \
        -f "Font Awesome 5 Free:style=Solid:size=16" \
        -f "Font Awesome 5 Brands:size=16" &

hc and , raise_monitor main , focus_monitor main \
        , compare tags.by-name.kitty.client_count = 0 \
        , use kitty , spawn kitty

