#!/bin/bash

hc() {
    herbstclient "$@"
}

# keybindings
Mod=Mod4
c=$HOME/.config/herbstluftwm

x="$c/brightness.sh"
hc keybind XF86MonBrightnessUp spawn "$x" +
hc keybind XF86MonBrightnessDown spawn "$x" -

x="$c/sound-ctl.sh"
hc keybind $Mod-XF86AudioMute spawn "$x" o
hc keybind XF86AudioMute spawn "$x" m
hc keybind XF86AudioRaiseVolume spawn "$x" +
hc keybind XF86AudioLowerVolume spawn "$x" -

