#!/bin/bash

hc() {
    herbstclient "$@"
}

hc pad main 48

killall -9 hermes lemonbar

hermes -l -s '  ' -p bar bar | lemonbar \
        -B '#00100010' \
        -f "Go Regular:size=12" \
        -f "Font Awesome 5 Free:style=Regular:size=16" \
        -f "Font Awesome 5 Free:style=Solid:size=16" \
        -f "Font Awesome 5 Brands:size=16" &

