#!/bin/bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#000'

hc detect_monitors
hc rename_monitor 0 main
hc pad main 48

hc set default_frame_layout 2

hc add tty
hc merge_tag default tty
hc add web

# keybindings
hc keyunbind --all
Mod=Mod4

hc keybind $Mod-Shift-q    quit
hc keybind $Mod-Shift-r    reload
hc keybind $Mod-Shift-x    remove
hc keybind $Mod-Shift-Return floating toggle
hc keybind $Mod-Return     fullscreen toggle
hc keybind $Mod-z          cycle
hc keybind $Mod-i          jumpto urgent

hc keybind $Mod-x substitute cc tags.focus.client_count or \
        ,, and \
                , compare tags.focus.frame_count = 1 \
                , compare cc = 1 \
        ,, and \
                , compare tags.focus.frame_count lt 4 \
                , compare tags.focus.frame_count lt cc \
                , chain _ focus l _ remove _ remove _ remove _ true \
                , split l , shift l , focus r \
                , chain \
                        __ and \
                                _ compare tags.focus.frame_count lt cc \
                                _ split t _ shift u _ focus d \
                        __ and \
                                _ compare tags.focus.frame_count lt cc \
                                _ split t _ shift u _ focus d \
                        __ focus l \
                        __ true \
        ,, and , remove , remove , remove

hc keybind $Mod-c close_and_remove

hc keybind $Mod-w focus u
hc keybind $Mod-a focus l
hc keybind $Mod-s focus d
hc keybind $Mod-d focus r

hc keybind $Mod-Shift-w resize u +0.02
hc keybind $Mod-Shift-a resize l +0.02
hc keybind $Mod-Shift-s resize d +0.02
hc keybind $Mod-Shift-d resize r +0.02

hc keybind $Mod-Tab or \
        ,, and \
                , compare tags.focus.name = tty \
                , or \
                        __ compare tags.focus.client_count = 0 \
                        __ and \
                                _ compare tags.focus.frame_count gt 1 \
                                _ split b _ focus d \
                        __ and \
                                _ split r _ focus r \
                        __ true \
                , spawn st \
        ,, and \
                , compare tags.focus.name \!= tty \
                , use tty \
                , compare tags.focus.client_count = 0 \
                , spawn st

hc keybind $Mod-f and \
        , use web , compare tags.focus.client_count = 0 \
        , spawn google-chrome-stable

tc=$(hc attr tags.count)
i=2
while [[ $i -lt $tc ]]; do
        hc keybind $Mod-$(( i - 1 )) use_index $i
        i=$(( i + 1 ))
done

c=$HOME/.config/herbstluftwm

hc keybind $Mod-space spawn rofi -modi window -show window
hc keybind $Mod-Shift-space spawn "$c/run.sh"

hc keybind Print spawn "$c/print.sh"

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# keybindings
Mod=Mod4
c=$HOME/.config/herbstluftwm

x="$c/brightness.sh"
hc keybind XF86MonBrightnessUp spawn "$x" +
hc keybind XF86MonBrightnessDown spawn "$x" -

x="$c/sound-ctl.sh"
hc keybind $Mod-XF86AudioMute spawn "$x" card
hc keybind XF86AudioMute spawn "$x" set Playback toggle-mute
hc keybind XF86AudioRaiseVolume spawn "$x" set Playback 3dB+
hc keybind XF86AudioLowerVolume spawn "$x" set Playback 3dB-

hc keybind $Mod-p spawn "$c/display.sh"

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_width 4
hc set frame_border_active_color '#ffafc7'
hc set frame_border_normal_color '#74d7ec'
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 16

hc attr theme.active.color '#ffafc7'
hc attr theme.normal.color '#74d7ec'
hc attr theme.urgent.color '#ee925d'
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 0
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#ffafc7'
hc attr theme.active.outer_color '#ffafc7'
hc attr theme.normal.inner_color '#74d7ec'
hc attr theme.normal.outer_color '#74d7ec'
hc attr theme.background_color '#100010'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set tree_style '╾│ ├└╼─┐'

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule class~'Firefox' tag=web
hc rule class~'google-chrome' tag=web
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

# hc -i | while read -r event winid _; do
#         [[ $event != reload ]] || break
#         [[ $event == focus_changed ]] || continue
#         [[ $winid == 0x0 ]] || continue
#         sleep 0.1
#         hc and , compare tags.focus.curframe_wcount = 0 , remove
#         sleep 0.25
#         hc and \
#                 , compare tags.focus.client_count = 0 \
#                 , use tty \
#                 , compare tags.focus.client_count = 0 \
#                 , spawn st
# done

killall -9 hermes
hc spawn hermes bar

hc and , raise_monitor main , focus_monitor main \
        , compare tags.by-name.tty.client_count = 0 \
        , use tty , spawn st

