colorscheme dedelala

set global ui_options ncurses_enable_mouse=false ncurses_assistant=cat ncurses_set_title=false

set global indentwidth 8
set global tabstop 8
set global aligntab false
set global scrolloff 4,4

hook global WinCreate .* %{
    addhl window/ show-matching
    addhl window/ number-lines -relative -hlcursor -separator "  "
    addhl window/ column 81 white,rgb:2d0040
    addhl window/ dynregex \h+$ 0:black,rgb:545453
    addhl window/ dynregex ^\t* 0:black,rgb:2d0040
    addhl window/ dynregex ^\ * 0:black,rgb:000f40
    addhl window/ dynregex \ +\t+\ * 0:black,rgb:d22323
    addhl window/ dynregex \t+\ +\t* 0:black,rgb:d22323
    addhl window/ dynregex ^[<=>]{7} 0:rgb:ff6666
    map window user -docstring "<--" , :buffer-previous<ret>
    map window user -docstring "-->" . :buffer-next<ret>
    map window user -docstring "blame" b :git\ blame<ret>
    map window user -docstring "hide blame" n :git\ hide-blame<ret>
    map window user -docstring "diff" d :git\ diff<ret>
    map window user -docstring "comment" c :comment-line<ret>
    map window user -docstring "lint" l :lint<ret>:buffer\ *lint-output*<ret>
    map window user -docstring "make" m :make<ret>:buffer\ *make*<ret>
    map window user -docstring "split" <space> :split<ret>
    map window user -docstring "shell" <tab> :shell<ret>
    map window user -docstring "find conflicts" X :grep\ -RE\ '^<lt>{7}'\ .<ret>
    map window user -docstring "next conflict" x /^<lt>{7}<ret>?^<gt>{7}<ret>Gl
    map window user -docstring "resolve keep a" <lt> s^<lt>{7}<ret>Xd/^={7}<ret>?^<gt>{7}<ret>Xd
    map window user -docstring "resolve keep b" <gt> s^<lt>{7}<ret>?^={7}<ret>Xd/^<gt>{7}<ret>Xd
}

define-command shell %{ nop %sh{
    kitty @ new-window --no-response --cwd="$(dirname "$kak_buffile")"
}}

define-command split %{ evaluate-commands %sh{
    if [[ $kak_client_list =~ client0 ]]; then
        echo rename-client adelaide
        echo new rename-client brunhilde
        exit
    fi

    for c in brunhilde cassandra desdemona esperanza friedegarde; do
        if ! [[ $kak_client_list =~ $c ]]; then
            echo new rename-client $c
            exit
        fi
    done

    echo echo you have enough
}}

hook global KakBegin .* %sh{
    echo rename-session \"$(basename "$PWD")\"
}

hook global BufWritePost .* git\ show-diff

hook global WinSetOption filetype=go %{
    set global indentwidth 0
    set global tabstop 8
    set window lintcmd 'sync; gofmt 2>&1 1>/dev/null'
    set window makecmd 'go build'
    set window disabled_hooks .*-indent
    go-enable-autocomplete
    hook buffer BufWritePre .* %{
        go-format -use-goimports
        lint
    }
    map window user -docstring "go doc" ? :go-doc-info<ret>
    map window user -docstring "go jump" / :go-jump<ret>
}

hook global WinSetOption filetype=python %{
    set window indentwidth 4
    set window tabstop 4
    set window lintcmd 'flake8 --ignore=E501'
    set window formatcmd 'yapf'
    lint-enable
    hook buffer BufWritePost .* lint
}

hook global WinSetOption filetype=ruby %{
    set window indentwidth 2
    set window tabstop 2
    set window lintcmd 'rubocop --format c --cache false'
    lint-enable
    hook buffer BufWritePost .* lint
}

hook global WinSetOption filetype=sh %{
    set window indentwidth 4
    set window tabstop 4
    set window lintcmd 'shellcheck -fgcc -Cnever'
    lint-enable
    hook buffer BufWritePost .* lint
}

hook global WinSetOption filetype=hcl %{
    set window indentwidth 2
    set window tabstop 2
    set window formatcmd 'terraform fmt -'
    hook buffer BufWritePre .* format
    # hook buffer BufWritePost .* tf-validate
}

hook global WinSetOption filetype=yaml %{
    set window indentwidth 2
    set window tabstop 2
    set window lintcmd 'yamllint -d ~/.yamllint.yml -f parsable "$kak_buffile"'
    lint-enable
    hook buffer BufWritePost .* lint
}

