#!/bin/bash

hc() {
    herbstclient "$@"
}

hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_width 4
hc set frame_border_active_color '#ffafc7'
hc set frame_border_normal_color '#74d7ec'
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 5
hc set frame_gap 16

hc attr theme.active.color '#ffafc7'
hc attr theme.normal.color '#74d7ec'
hc attr theme.urgent.color '#ee925d'
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 0
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#ffafc7'
hc attr theme.active.outer_color '#ffafc7'
hc attr theme.normal.inner_color '#74d7ec'
hc attr theme.normal.outer_color '#74d7ec'
hc attr theme.background_color '#100010'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set tree_style '╾│ ├└╼─┐'

