#!/bin/bash

hc() {
    herbstclient "$@"
}

hc rule hook=new_split_maybe

killall -9 herbstclient

winids=""
hc -i | while read -r hook value winid; do
        case $hook in
        window_title_changed)
                if [[ -z $value ]]; then
                        hc and \
                                , compare tags.focus.curframe_wcount = 0 \
                                , remove \
                                , compare tags.focus.client_count = 0 \
                                , use kitty
                fi
                ;;
        rule)
                if [[ $winids =~ $winid ]]; then
                        continue
                fi
                winids="$winids $winid"
                if [[ $value == "new_split_maybe" ]]; then
                        hc and \
                                ,, compare clients.focus.pseudotile = false \
                                ,, compare tags.focus.curframe_wcount gt 1 \
                                ,, or \
                                        , and \
                                                - compare tags.focus.frame_count gt 1 \
                                                - split vert \
                                                - shift d \
                                        , and \
                                                - split horz \
                                                - shift r
                fi
                ;;
        reload)
                return;
                ;;
        esac
done &

